---
title: "day-3"
author: "Byron"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: united
    toc: true
    toc_float: true
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sf)
library(leaflet)
library(extrafont)
library(tidygeocoder)
library(classInt)
library(stringr)

# font_import()  # This may take some time
# loadfonts()

```

# Data

```{r}
preschools <- read.csv("./Data/ListingofCentres.csv")
sg <- st_read("./Data/mp2019PAs_new.geojson")
ref <- read.csv("./Data/SG_postal.csv")
# pop <- read_csv("./Data/populationPA.csv")
```

```{r}
preschools <- preschools %>%
  select(centre_name, postal_code)

joined_data <- preschools %>%
  left_join(ref, by = "postal_code")

sf_use_s2(FALSE)

cleaned_joined_data <- joined_data %>%
  filter(!is.na(lon) & !is.na(lat))

joined_points <- cleaned_joined_data %>%
  st_as_sf(coords = c("lon", "lat"), crs = st_crs(sg))

counts_data <- sg %>%
  st_join(joined_points, join = st_contains) %>%
  group_by(PLN_AREA_N, geometry) %>%
  summarise(counts = n(), .groups = "drop") %>% 
  st_zm() 


counts_data <- counts_data %>%
  mutate(PLN_AREA_N = tolower(PLN_AREA_N))

pop <- read.csv("./Data/day3_pop.csv")


# pop <- pop %>%
#   mutate(PLN_AREA_N = tolower(Number))
# 
# 
# counts_data <- counts_data %>%
#   left_join(pop, by = "PLN_AREA_N")


```

## Join population data from wikipedia

```{r}
counts_data <- counts_data %>%
  mutate(PLN_AREA_N = str_to_title(PLN_AREA_N))

joined_data <- counts_data %>%
  left_join(pop, by = c("PLN_AREA_N" = "Name"))

joined_data <- joined_data %>%
  mutate(Population = as.numeric(gsub(",", "", Population)))

joined_data <- joined_data %>%
  mutate(density = counts / Population)

joined_data <- joined_data %>%
  mutate(density = if_else(Population < 200, NA, density))
```

# Map

```{r}

breaks <- classIntervals(joined_data$density, n = 5, style = "jenks")
joined_data$group <- cut(joined_data$density, breaks = breaks$brks, include.lowest = TRUE)

library(dplyr)

joined_data <- joined_data %>%
  mutate(band = case_when(
    group == "[0.000389,0.000577]" ~ "1st group (lowest density)",
    group == "(0.000901,0.00164]" ~ "3rd group",
    group == "(0.00333,0.0045]" ~ "5th group (highest density)",
    group == "(0.00164,0.00333]" ~ "4th group",
    group == "(0.000577,0.000901]" ~ "2nd group",
    TRUE ~ NA_character_  # Fallback for any unmatched groups
  ))

joined_data <- joined_data %>%
  mutate(band = factor(band, levels = c("1st group (lowest density)", "2nd group", "3rd group", "4th group", "5th group (highest density)")))

plot3 <- ggplot() +
  geom_sf(data = joined_data, aes(fill = band), color = "white") +  # Fill based on the group
  scale_fill_manual(values = c("#D5D5BC", "#B3B488", "#A59132", "#758448", "#483D03"), 
                    name = "Density of preschools\n(weighted by population\nin Planning Area)", na.value = "lightgray") +
  theme_minimal(base_family = "Lato") + 
  labs(
    title = 'Playful Polygons: Preschool Density Map by Planning Area',
    subtitle = "The allure of Central Area applies to preschoolers too..."
  ) +
  annotate(
    "text", x = 104.052232, y = 1.2,
    label = "30DayMapChallenge\nDay #3\nPlayful Polygons\nByron",
    color = "#7f8181", size = 3, hjust = 1, vjust = 1,
    family = "Lato"
  ) +
  annotate(
    "text", x = 103.609410, y = 1.192789,
    label = "",
    color = "#7f8181", size = 2, hjust = 0, vjust = 1,
    family = "Lato"
  ) +
  theme(
    plot.title = element_text(size = 14, face = "bold", family = "Lato Black"), 
    axis.title = element_blank(),
    axis.text = element_blank(),
    panel.grid = element_blank()
  )

plot3
```

```{r}

png("03-Byron-Polygons.png", width = 3200, height = 2100, res = 300)

# Print the plot to the device
print(plot3)

# Close the device
dev.off()
```
