---
title: "day-20"
author: "Byron"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: united
    toc: true
    toc_float: true
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sf)
library(leaflet)
library(extrafont)
library(tidygeocoder)
library(classInt)
library(purrr)
library(viridis)
library(ggtext)
library(extrafont)
library(ggimage)
library(stringr)

options(scipen = 999)

# font_import()  
# loadfonts()

```

# Data

## Layers

Note that embassies layer is obtained using QuickOSM in QGIS

```{r}
land <- st_read("./Data/day-20-clips/day-20-land.geojson")
sea <- st_read("./Data/day-20-clips/day-20-sea.geojson")
embassies <- st_read("./Data/embassies-sg-20241120-2.geojson")
mrt <- st_read("./Data/day-20-clips/day-20-mrt.geojson")

```

Quite straightforward map, no geoprocessing needed...

## Map

```{r}
plot20 <- ggplot() +
  geom_sf(data = land, fill = "#f7f7f0", color = "white", size = 5) +
  geom_sf(data = sea, fill = "#b8e5f8", color = "white", size = 5) +
  geom_sf(data = mrt, color = "#e1e1da", size = 1.5) +  
  geom_sf(data = embassies, color = "#53451f", size = 1.5) +   
  theme_minimal(base_family = "Lato") +  # Set base font to Lato
  labs(
    title = 'Diplomatic Missions and Embassies in Singapore (Via OSM)',
    subtitle = "Are they clustered or dispersed?\nFor detailed point pattern statistical analysis results, subscribe to Byron Premium today!"
  ) +
  annotate(
    "text", x = 103.91, y = 1.26,                      
    label = "30DayMapChallenge\nDay #20\nEmbassies Everywhere\nData: OpenStreetMap\nByron",
    color = "#7f8181", size = 3, hjust = 1, vjust = 1,
    family = "Lato"  # Use Lato for annotation text
  ) +
  theme(
    plot.title = element_text(size = 14, face = "bold", family = "Lato Black"),  # Use Lato Black for the title
    axis.title = element_blank(),
    axis.text = element_blank(),
    panel.grid = element_blank()    
  )

plot20
```

```{r}

png("20-Byron-OSM.png", width = 2100, height = 2100, res = 300)

# Print the plot to the device
print(plot20)

# Close the device
dev.off()

```
